version: 1.0.{build}
environment:
  ASPNETCORE_ENVIRONMENT: appveyor
  COVERALLS_REPO_TOKEN:
    secure: Aib0dt/M2yLE5OAyHD33ENZU7MbUhDdGpVf/WDd+ECgOV7TEBrPN3tiMfqZrvCAj
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
  - dotnet tool install --global coveralls.net
services:
  - mssql2017
nuget:
  disable_publish_on_pr: false
before_build:
- cmd: dotnet restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
test_script:
  - dotnet test --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_test:
  - <NUGET_PACKAGE_ROOT>\coveralls.net\0.7.0\tools\csmacnz.Coveralls.exe --opencover -i --useRelativePaths
artifacts:
- path: src\FluentCommander\bin\Release\*.nupkg
  name: NuGet
deploy:
- provider: Environment
  name: NuGet