version: 1.0.{build}
environment:
  ASPNETCORE_ENVIRONMENT: appveyor
  COVERALLS_REPO_TOKEN:
    secure: Aib0dt/M2yLE5OAyHD33ENZU7MbUhDdGpVf/WDd+ECgOV7TEBrPN3tiMfqZrvCAj
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
  - dotnet tool install --global coveralls.net
services:
  - mssql2017
nuget:
  disable_publish_on_pr: false
before_build:
- cmd: dotnet restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
#test_script:
#  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

#after_test:
#  - dotnet test -c Debug -f netcoreapp3.1 tests/FluentCommander.IntegrationTests.SqlServer/FluentCommander.IntegrationTests.SqlServer.csproj --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
#  - .\tools\csmacnz.Coveralls --opencover -i tests/FluentCommander.IntegrationTests.SqlServer/coverage.opencover.xml --useRelativePaths


#after_test:
#  - csmacnz.coveralls --useRelativePaths --multiple --input "opencover=tests\FluentCommander.UnitTests\coverage.netcoreapp3.1.opencover.xml;opencover=tests\FluentCommander.IntegrationTests.SqlServer\coverage.netcoreapp3.1.opencover.xml"

test_script:
- ps: >-
    nuget install xunit.runner.console -OutputDirectory packages -Version 2.3.1    
    nuget install OpenCover -OutputDirectory packages -Version 4.6.166
    
    .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:dotnet.exe "-targetargs:"".\packages\xunit.runner.console.2.3.1\tools\netcoreapp2.0\xunit.console.dll"" ""tests\FluentCommander.IntegrationTests.SqlServer\bin\Debug\netcoreapp3.1\FluentCommander.IntegrationTests.SqlServer.dll"" -noshadow -appveyor" -filter:"+[FluentCommander*]*" -oldStyle -output:opencoverCoverage.xml
    $coveralls = ".\tools\csmacnz.coveralls.exe"
    $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID


artifacts:
- path: src\FluentCommander\bin\Release\*.nupkg
  name: NuGet
deploy:
- provider: Environment
  name: NuGet